# Use an official Tomcat runtime as a parent image
FROM tomcat:9.0

# Set the working directory inside the container
WORKDIR /usr/local/tomcat/webapps/

# Copy the Spring Boot application WAR file to the Tomcat webapps directory
COPY target/final-0.0.1-SNAPSHOT.war ./ROOT.war

# Expose port 8080 to the outside world
EXPOSE 8080

# Run Tomcat
CMD ["catalina.sh", "run"]